; Under Bed Light - ESP32-C3 mini
; Source: D:\Arduino Daten\ArduinoProgramme\BedLight_PIR\BedLight_PIR.ino
[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
