[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2
    dfrobot/DFRobot_ENS160
    adafruit/Adafruit HDC1000 Library
    adafruit/Adafruit NeoPixel
    knolleary/PubSubClient
    olikraus/U8g2_for_Adafruit_GFX